nameOverride: argocd
crds:
  keep: false
global:
  additionalLabels:
    fargate_ready: "true"
  domain: argo-infra.x.y
controller:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
configs:
  params:
    server.insecure: true
    reposerver.max.combined.directory.manifests.size: "230M"
server:
  logLevel: info
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  ingress:
    enabled: true
    ingressClassName: Z-ingress
repoServer:
  replicas: 1
  env:
    - name: "ARGOCD_EXEC_TIMEOUT"
      value: "300"
  logLevel: info
  resources:
    requests:
      cpu: 500m
      memory: 64Mi
